language: node_js
node_js:
  - "node"
  - "10.16.0"

addons:
  chrome: stable
before_install:
  npm install karma-cli -g
install:
  npm  install
services:
  - xvfb
script:
  - karma start karma.conf.js --single-run
