language: node_js
node_js:
  - 10
services:
  - xvfb
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
install:
  - npm install -g karma-cli
  - npm install
script:
  - npm run test
