language: node_js
node_js:
  - 10
services:
  - xvfb
addons:
      chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - npm install -g karma-cli
  - npm install
script:
  - npm run start
